/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.purejosh.pureberries.init;

import net.purejosh.pureberries.item.SweetBerryTartItem;
import net.purejosh.pureberries.item.SweetBerryMuffinItem;
import net.purejosh.pureberries.item.SweetBerryJuiceItem;
import net.purejosh.pureberries.item.SweetBerryJamSandwichItem;
import net.purejosh.pureberries.item.SweetBerryJamItem;
import net.purejosh.pureberries.item.SweetBerryBiscuitItem;
import net.purejosh.pureberries.item.SweetBerriesHoneyDippedItem;
import net.purejosh.pureberries.item.SweetBerriesCookedItem;
import net.purejosh.pureberries.item.SweetBerriesCocoaCoveredItem;
import net.purejosh.pureberries.item.GojiBerryTartItem;
import net.purejosh.pureberries.item.GojiBerryMuffinItem;
import net.purejosh.pureberries.item.GojiBerryJuiceItem;
import net.purejosh.pureberries.item.GojiBerryJamSandwichItem;
import net.purejosh.pureberries.item.GojiBerryJamItem;
import net.purejosh.pureberries.item.GojiBerryBiscuitItem;
import net.purejosh.pureberries.item.GojiBerriesItem;
import net.purejosh.pureberries.item.GojiBerriesHoneyDippedItem;
import net.purejosh.pureberries.item.GojiBerriesCookedItem;
import net.purejosh.pureberries.item.GojiBerriesCocoaCoveredItem;
import net.purejosh.pureberries.item.GlowBerryTartItem;
import net.purejosh.pureberries.item.GlowBerryMuffinItem;
import net.purejosh.pureberries.item.GlowBerryJuiceItem;
import net.purejosh.pureberries.item.GlowBerryJamSandwichItem;
import net.purejosh.pureberries.item.GlowBerryJamItem;
import net.purejosh.pureberries.item.GlowBerryBiscuitItem;
import net.purejosh.pureberries.item.GlowBerriesHoneyDippedItem;
import net.purejosh.pureberries.item.GlowBerriesCookedItem;
import net.purejosh.pureberries.item.GlowBerriesCocoaCoveredItem;
import net.purejosh.pureberries.item.CloudberryTartItem;
import net.purejosh.pureberries.item.CloudberryMuffinItem;
import net.purejosh.pureberries.item.CloudberryJuiceItem;
import net.purejosh.pureberries.item.CloudberryJamSandwichItem;
import net.purejosh.pureberries.item.CloudberryJamItem;
import net.purejosh.pureberries.item.CloudberryBiscuitItem;
import net.purejosh.pureberries.item.CloudberriesItem;
import net.purejosh.pureberries.item.CloudberriesHoneyDippedItem;
import net.purejosh.pureberries.item.CloudberriesCookedItem;
import net.purejosh.pureberries.item.CloudberriesCocoaCoveredItem;
import net.purejosh.pureberries.item.BlueberryTartItem;
import net.purejosh.pureberries.item.BlueberryMuffinItem;
import net.purejosh.pureberries.item.BlueberryJuiceItem;
import net.purejosh.pureberries.item.BlueberryJamSandwichItem;
import net.purejosh.pureberries.item.BlueberryJamItem;
import net.purejosh.pureberries.item.BlueberryBiscuitItem;
import net.purejosh.pureberries.item.BlueberriesItem;
import net.purejosh.pureberries.item.BlueberriesHoneyDippedItem;
import net.purejosh.pureberries.item.BlueberriesCookedItem;
import net.purejosh.pureberries.item.BlueberriesCocoaCoveredItem;
import net.purejosh.pureberries.PureberriesMod;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;

public class PureberriesModItems {
	public static Item SWEET_BERRIES_COOKED;
	public static Item SWEET_BERRIES_COCOA_COVERED;
	public static Item SWEET_BERRIES_HONEY_DIPPED;
	public static Item SWEET_BERRY_BISCUIT;
	public static Item SWEET_BERRY_MUFFIN;
	public static Item SWEET_BERRY_TART;
	public static Item SWEET_BERRY_JUICE;
	public static Item SWEET_BERRY_JAM;
	public static Item SWEET_BERRY_JAM_SANDWICH;
	public static Item BLUEBERRIES;
	public static Item BLUEBERRIES_COOKED;
	public static Item BLUEBERRIES_COCOA_COVERED;
	public static Item BLUEBERRIES_HONEY_DIPPED;
	public static Item BLUEBERRY_BISCUIT;
	public static Item BLUEBERRY_MUFFIN;
	public static Item BLUEBERRY_TART;
	public static Item BLUEBERRY_JUICE;
	public static Item BLUEBERRY_JAM;
	public static Item BLUEBERRY_JAM_SANDWICH;
	public static Item CLOUDBERRIES;
	public static Item CLOUDBERRIES_COOKED;
	public static Item CLOUDBERRIES_COCOA_COVERED;
	public static Item CLOUDBERRIES_HONEY_DIPPED;
	public static Item CLOUDBERRY_BISCUIT;
	public static Item CLOUDBERRY_MUFFIN;
	public static Item CLOUDBERRY_TART;
	public static Item CLOUDBERRY_JUICE;
	public static Item CLOUDBERRY_JAM;
	public static Item CLOUDBERRY_JAM_SANDWICH;
	public static Item GOJI_BERRIES;
	public static Item GOJI_BERRIES_COOKED;
	public static Item GOJI_BERRIES_COCOA_COVERED;
	public static Item GOJI_BERRIES_HONEY_DIPPED;
	public static Item GOJI_BERRY_BISCUIT;
	public static Item GOJI_BERRY_MUFFIN;
	public static Item GOJI_BERRY_TART;
	public static Item GOJI_BERRY_JUICE;
	public static Item GOJI_BERRY_JAM;
	public static Item GOJI_BERRY_JAM_SANDWICH;
	public static Item GLOW_BERRIES_COOKED;
	public static Item GLOW_BERRIES_COCOA_COVERED;
	public static Item GLOW_BERRIES_HONEY_DIPPED;
	public static Item GLOW_BERRY_BISCUIT;
	public static Item GLOW_BERRY_MUFFIN;
	public static Item GLOW_BERRY_TART;
	public static Item GLOW_BERRY_JUICE;
	public static Item GLOW_BERRY_JAM;
	public static Item GLOW_BERRY_JAM_SANDWICH;
	public static Item BLUEBERRY_BUSH_PLANT_STAGE_0;
	public static Item BLUEBERRY_BUSH_PLANT_STAGE_1;
	public static Item BLUEBERRY_BUSH_PLANT_STAGE_2;
	public static Item BLUEBERRY_BUSH_PLANT_STAGE_3;
	public static Item GOJI_BERRY_BUSH_STAGE_0;
	public static Item GOJI_BERRY_BUSH_STAGE_1;
	public static Item GOJI_BERRY_BUSH_STAGE_2;
	public static Item GOJI_BERRY_BUSH_STAGE_3;
	public static Item GOJI_BERRY_BUSH_STAGE_4;
	public static Item GOJI_BERRY_BUSH_STAGE_5;
	public static Item GOJI_BERRY_BUSH_STAGE_6;
	public static Item GOJI_BERRY_BUSH_STAGE_7;
	public static Item CLOUDBERRY_PLANT_STAGE_0;
	public static Item CLOUDBERRY_PLANT_STAGE_1;
	public static Item CLOUDBERRY_PLANT_STAGE_2;
	public static Item CLOUDBERRY_PLANT_STAGE_3;
	public static Item BLUEBERRY_BUSH_STAGE_0;
	public static Item BLUEBERRY_BUSH_STAGE_1;
	public static Item BLUEBERRY_BUSH_STAGE_2;
	public static Item BLUEBERRY_BUSH_STAGE_3;

	public static void load() {
		SWEET_BERRIES_COOKED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "sweet_berries_cooked"), new SweetBerriesCookedItem());
		SWEET_BERRIES_COCOA_COVERED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "sweet_berries_cocoa_covered"), new SweetBerriesCocoaCoveredItem());
		SWEET_BERRIES_HONEY_DIPPED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "sweet_berries_honey_dipped"), new SweetBerriesHoneyDippedItem());
		SWEET_BERRY_BISCUIT = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "sweet_berry_biscuit"), new SweetBerryBiscuitItem());
		SWEET_BERRY_MUFFIN = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "sweet_berry_muffin"), new SweetBerryMuffinItem());
		SWEET_BERRY_TART = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "sweet_berry_tart"), new SweetBerryTartItem());
		SWEET_BERRY_JUICE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "sweet_berry_juice"), new SweetBerryJuiceItem());
		SWEET_BERRY_JAM = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "sweet_berry_jam"), new SweetBerryJamItem());
		SWEET_BERRY_JAM_SANDWICH = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "sweet_berry_jam_sandwich"), new SweetBerryJamSandwichItem());
		BLUEBERRIES = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberries"), new BlueberriesItem());
		BLUEBERRIES_COOKED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberries_cooked"), new BlueberriesCookedItem());
		BLUEBERRIES_COCOA_COVERED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberries_cocoa_covered"), new BlueberriesCocoaCoveredItem());
		BLUEBERRIES_HONEY_DIPPED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberries_honey_dipped"), new BlueberriesHoneyDippedItem());
		BLUEBERRY_BISCUIT = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_biscuit"), new BlueberryBiscuitItem());
		BLUEBERRY_MUFFIN = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_muffin"), new BlueberryMuffinItem());
		BLUEBERRY_TART = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_tart"), new BlueberryTartItem());
		BLUEBERRY_JUICE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_juice"), new BlueberryJuiceItem());
		BLUEBERRY_JAM = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_jam"), new BlueberryJamItem());
		BLUEBERRY_JAM_SANDWICH = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_jam_sandwich"), new BlueberryJamSandwichItem());
		CLOUDBERRIES = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberries"), new CloudberriesItem());
		CLOUDBERRIES_COOKED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberries_cooked"), new CloudberriesCookedItem());
		CLOUDBERRIES_COCOA_COVERED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberries_cocoa_covered"), new CloudberriesCocoaCoveredItem());
		CLOUDBERRIES_HONEY_DIPPED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberries_honey_dipped"), new CloudberriesHoneyDippedItem());
		CLOUDBERRY_BISCUIT = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberry_biscuit"), new CloudberryBiscuitItem());
		CLOUDBERRY_MUFFIN = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberry_muffin"), new CloudberryMuffinItem());
		CLOUDBERRY_TART = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberry_tart"), new CloudberryTartItem());
		CLOUDBERRY_JUICE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberry_juice"), new CloudberryJuiceItem());
		CLOUDBERRY_JAM = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberry_jam"), new CloudberryJamItem());
		CLOUDBERRY_JAM_SANDWICH = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberry_jam_sandwich"), new CloudberryJamSandwichItem());
		GOJI_BERRIES = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berries"), new GojiBerriesItem());
		GOJI_BERRIES_COOKED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berries_cooked"), new GojiBerriesCookedItem());
		GOJI_BERRIES_COCOA_COVERED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berries_cocoa_covered"), new GojiBerriesCocoaCoveredItem());
		GOJI_BERRIES_HONEY_DIPPED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berries_honey_dipped"), new GojiBerriesHoneyDippedItem());
		GOJI_BERRY_BISCUIT = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_biscuit"), new GojiBerryBiscuitItem());
		GOJI_BERRY_MUFFIN = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_muffin"), new GojiBerryMuffinItem());
		GOJI_BERRY_TART = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_tart"), new GojiBerryTartItem());
		GOJI_BERRY_JUICE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_juice"), new GojiBerryJuiceItem());
		GOJI_BERRY_JAM = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_jam"), new GojiBerryJamItem());
		GOJI_BERRY_JAM_SANDWICH = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_jam_sandwich"), new GojiBerryJamSandwichItem());
		GLOW_BERRIES_COOKED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "glow_berries_cooked"), new GlowBerriesCookedItem());
		GLOW_BERRIES_COCOA_COVERED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "glow_berries_cocoa_covered"), new GlowBerriesCocoaCoveredItem());
		GLOW_BERRIES_HONEY_DIPPED = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "glow_berries_honey_dipped"), new GlowBerriesHoneyDippedItem());
		GLOW_BERRY_BISCUIT = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "glow_berry_biscuit"), new GlowBerryBiscuitItem());
		GLOW_BERRY_MUFFIN = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "glow_berry_muffin"), new GlowBerryMuffinItem());
		GLOW_BERRY_TART = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "glow_berry_tart"), new GlowBerryTartItem());
		GLOW_BERRY_JUICE = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "glow_berry_juice"), new GlowBerryJuiceItem());
		GLOW_BERRY_JAM = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "glow_berry_jam"), new GlowBerryJamItem());
		GLOW_BERRY_JAM_SANDWICH = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "glow_berry_jam_sandwich"), new GlowBerryJamSandwichItem());
		BLUEBERRY_BUSH_PLANT_STAGE_0 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_bush_plant_stage_0"), new BlockItem(PureberriesModBlocks.BLUEBERRY_BUSH_PLANT_STAGE_0, new Item.Properties()));
		BLUEBERRY_BUSH_PLANT_STAGE_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_bush_plant_stage_1"), new BlockItem(PureberriesModBlocks.BLUEBERRY_BUSH_PLANT_STAGE_1, new Item.Properties()));
		BLUEBERRY_BUSH_PLANT_STAGE_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_bush_plant_stage_2"), new BlockItem(PureberriesModBlocks.BLUEBERRY_BUSH_PLANT_STAGE_2, new Item.Properties()));
		BLUEBERRY_BUSH_PLANT_STAGE_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_bush_plant_stage_3"), new BlockItem(PureberriesModBlocks.BLUEBERRY_BUSH_PLANT_STAGE_3, new Item.Properties()));
		GOJI_BERRY_BUSH_STAGE_0 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_bush_stage_0"), new BlockItem(PureberriesModBlocks.GOJI_BERRY_BUSH_STAGE_0, new Item.Properties()));
		GOJI_BERRY_BUSH_STAGE_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_bush_stage_1"), new BlockItem(PureberriesModBlocks.GOJI_BERRY_BUSH_STAGE_1, new Item.Properties()));
		GOJI_BERRY_BUSH_STAGE_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_bush_stage_2"), new BlockItem(PureberriesModBlocks.GOJI_BERRY_BUSH_STAGE_2, new Item.Properties()));
		GOJI_BERRY_BUSH_STAGE_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_bush_stage_3"), new BlockItem(PureberriesModBlocks.GOJI_BERRY_BUSH_STAGE_3, new Item.Properties()));
		GOJI_BERRY_BUSH_STAGE_4 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_bush_stage_4"), new BlockItem(PureberriesModBlocks.GOJI_BERRY_BUSH_STAGE_4, new Item.Properties()));
		GOJI_BERRY_BUSH_STAGE_5 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_bush_stage_5"), new BlockItem(PureberriesModBlocks.GOJI_BERRY_BUSH_STAGE_5, new Item.Properties()));
		GOJI_BERRY_BUSH_STAGE_6 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_bush_stage_6"), new BlockItem(PureberriesModBlocks.GOJI_BERRY_BUSH_STAGE_6, new Item.Properties()));
		GOJI_BERRY_BUSH_STAGE_7 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "goji_berry_bush_stage_7"), new BlockItem(PureberriesModBlocks.GOJI_BERRY_BUSH_STAGE_7, new Item.Properties()));
		CLOUDBERRY_PLANT_STAGE_0 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberry_plant_stage_0"), new BlockItem(PureberriesModBlocks.CLOUDBERRY_PLANT_STAGE_0, new Item.Properties()));
		CLOUDBERRY_PLANT_STAGE_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberry_plant_stage_1"), new BlockItem(PureberriesModBlocks.CLOUDBERRY_PLANT_STAGE_1, new Item.Properties()));
		CLOUDBERRY_PLANT_STAGE_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberry_plant_stage_2"), new BlockItem(PureberriesModBlocks.CLOUDBERRY_PLANT_STAGE_2, new Item.Properties()));
		CLOUDBERRY_PLANT_STAGE_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "cloudberry_plant_stage_3"), new BlockItem(PureberriesModBlocks.CLOUDBERRY_PLANT_STAGE_3, new Item.Properties()));
		BLUEBERRY_BUSH_STAGE_0 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_bush_stage_0"), new BlockItem(PureberriesModBlocks.BLUEBERRY_BUSH_STAGE_0, new Item.Properties()));
		BLUEBERRY_BUSH_STAGE_1 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_bush_stage_1"), new BlockItem(PureberriesModBlocks.BLUEBERRY_BUSH_STAGE_1, new Item.Properties()));
		BLUEBERRY_BUSH_STAGE_2 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_bush_stage_2"), new BlockItem(PureberriesModBlocks.BLUEBERRY_BUSH_STAGE_2, new Item.Properties()));
		BLUEBERRY_BUSH_STAGE_3 = Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(PureberriesMod.MODID, "blueberry_bush_stage_3"), new BlockItem(PureberriesModBlocks.BLUEBERRY_BUSH_STAGE_3, new Item.Properties()));
	}

	public static void clientLoad() {
	}
}
